sudo: false
language: python
python:
  - '3.5'
  - '3.6'
addons:
  postgresql: '9.5'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=">=1.11,<2.0"
    - DJANGO=">=2.0,<2.1"
install:
  - pip install -q coveralls coverage flake8 Django$DJANGO
  - pip install -r requirements/docs.txt
before_script:
  - psql -c 'CREATE DATABASE issue;' -U postgres
script:
  - flake8 .
  - coverage run setup.py test
  - coverage report --fail-under=100
  - python setup.py build_sphinx
after_success:
  coveralls
