# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 21:26

import django.db.models
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_auto_20180329_1522'),
    ]

    # The operations in this migration were AlterModel calls that were eliminated by adjusting
    # the CreateModel calls in 0001 (to eliminate needing to import the legacy jsonfield package)
    operations = []
