# Generated by Django 2.1.4 on 2018-12-10 18:57

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20180402_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responderaction',
            name='function_kwargs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
