# Generated by Django 2.1.4 on 2018-12-10 18:57

import django.db.models
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20180402_2126'),
    ]

    # The operations in this migration were AlterModel calls that were eliminated by adjusting
    # the CreateModel calls in 0001 (to eliminate needing to import the legacy jsonfield package)
    operations = []
