# Generated by Django 2.2.4 on 2019-08-20 15:45

from django.db import migrations, models
import django.db.models.deletion

from . import datamigrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('issue', '0004_auto_20181210_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='responder',
            name='allow_retry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issueaction',
            name='action_issue_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='issueaction',
            name='action_issue_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.RunPython(datamigrations.normalize_generic_issues),
        migrations.AlterField(
            model_name='issueaction',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='issue.Issue'),
        ),
    ]
