# Generated by Django 2.2.4 on 2019-08-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_auto_20181210_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='responder',
            name='allow_retry',
            field=models.BooleanField(default=False),
        ),
    ]
