# Generated by Django 2.2.4 on 2019-08-20 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('issue', '0005_responder_allow_retry'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueaction',
            name='action_issue_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='issueaction',
            name='action_issue_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
        ),
    ]
