# Generated by Django 2.2.4 on 2019-08-20 18:09
from django.db import migrations

from . import datamigrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_auto_20190820_1806'),
    ]

    operations = [
        migrations.RunPython(datamigrations.normalize_generic_issues)
    ]
