# Generated by Django 2.2.4 on 2019-08-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_auto_20190820_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueaction',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='issue.Issue'),
        ),
    ]
